name: Build and Push Image

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Reclaim disk space
        run: |
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache || true
          sudo rm -rf /usr/share/dotnet || true
          docker system prune --all --force --volumes || true

      - name: Configure image metadata
        run: ./configure --image-tag "${{ github.sha }}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: make docker-push
